// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reciicer.Data;

#nullable disable

namespace Reciicer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240514012018_ReciclagemTable")]
    partial class ReciclagemTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reciicer.Models.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NivelId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NivelId");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPF = "48906785062",
                            Email = "jurandir@gmail.com",
                            NivelId = 3,
                            Nome = "Jurandir",
                            PontuacaoTotal = 0,
                            Telefone = "(85)98792-0782"
                        },
                        new
                        {
                            Id = 2,
                            CPF = "48517494067",
                            Email = "judit@gmail.com",
                            NivelId = 2,
                            Nome = "Judit",
                            PontuacaoTotal = 0,
                            Telefone = "(69)99727-2310"
                        },
                        new
                        {
                            Id = 3,
                            CPF = "71134549504",
                            Email = "astolfo@gmail.com",
                            NivelId = 4,
                            Nome = "Astolfo",
                            PontuacaoTotal = 0,
                            Telefone = "(92)98308-7102"
                        });
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PontosPerdaFrequencia")
                        .HasColumnType("int");

                    b.Property<int>("PontuacaoNecessario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Nivel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Iniciante",
                            PontosPerdaFrequencia = 0,
                            PontuacaoNecessario = 0
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Básico",
                            PontosPerdaFrequencia = 2,
                            PontuacaoNecessario = 10
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Intermediário",
                            PontosPerdaFrequencia = 10,
                            PontuacaoNecessario = 50
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Avançado",
                            PontosPerdaFrequencia = 20,
                            PontuacaoNecessario = 200
                        });
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Reciclagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PontuacaoGanha")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Reciclagem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            DataOperacao = new DateTime(2024, 5, 13, 22, 20, 17, 906, DateTimeKind.Local).AddTicks(8817),
                            PontuacaoGanha = 10
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 1,
                            DataOperacao = new DateTime(2024, 5, 13, 22, 20, 17, 906, DateTimeKind.Local).AddTicks(8831),
                            PontuacaoGanha = 5
                        });
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Cliente", b =>
                {
                    b.HasOne("Reciicer.Models.Entities.Nivel", "Nivel")
                        .WithMany("Clientes")
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Reciclagem", b =>
                {
                    b.HasOne("Reciicer.Models.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Nivel", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
